#!/usr/bin/python


#Server rpc:
#Connection oriented:
#calls        badcalls     nullrecv     badlen       xdrcall      dupchecks    
#187128034265 0            0            0            0            4269012702   
#dupreqs      
#61349        
#Connectionless:
#calls        badcalls     nullrecv     badlen       xdrcall      dupchecks    
#4            0            0            0            0            0            
#dupreqs      
#0            
#Server NFSv2:
#calls        badcalls     referrals    referlinks   
#0            0            0            0            
#Server NFSv3:
#calls        badcalls     referrals    referlinks   
#186324616352 57179        0            0            
#Server NFSv4:
#calls        badcalls     referrals    referlinks   
#562966031    24283        0            0            
#Version 2: (0 calls)
#null     getattr  setattr  root     lookup   readlink read     wrcache  
#0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     
#write    create   remove   rename   link     symlink  mkdir    rmdir    
#0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     0 0%     
#readdir  statfs   
#0 0%     0 0%     
#Version 3: (186320997959 calls)
#null             getattr          setattr          lookup           
#633 0%           67440329332 36%  884784954 0%     7416926793 3%    
#access           readlink         read             write            
#103924108602 55% 451262 0%        3106396095 1%    801203973 0%     
#create           mkdir            symlink          mknod            
#294844119 0%     173156407 0%     10216 0%         0 0%             
#remove           rmdir            rename           link             
#271613284 0%     338493342 0%     43951601 0%      6 0%             
#readdir          readdirplus      fsstat           fsinfo           
#504910 0%        1460898950 0%    138496067 0%     310793 0%        
#pathconf         commit           
#155078 0%        24361542 0%      
#Version 4: (563005881 calls)
#null                compound            
#9 0%                563005872 99%       
#Version 4: (1935126651 operations)
#reserved            access              close               commit              
#0 0%                28378879 1%         125659247 6%        550464 0%           
#create              delegpurge          delegreturn         getattr             
#580522 0%           0 0%                9004069 0%          483450049 24%       
#getfh               link                lock                lockt               
#140715775 7%        12413 0%            84 0%               0 0%                
#locku               lookup              lookupp             nverify             
#72 0%               16816622 0%         0 0%                0 0%                
#open                openattr            open_confirm        open_downgrade      
#132442153 6%        0 0%                113372732 5%        425 0%              
#vputfh               putpubfh            putrootfh           read                
#563341230 29%       0 0%                24507 0%            15655076 0%         
#readdir             readlink            remove              rename              
#41382997 2%         12257 0%            3392446 0%          1389558 0%          
#renew               restorefh           savefh              secinfo             
#943838 0%           115928067 5%        117322949 6%        0 0%                
#setattr             setclientid         setclientid_confirm verify              
#7662392 0%          24561 0%            24562 0%            0 0%                
#write               release_lockowner   illegal             
#17038665 0%         40 0%               0 0%                
#Server nfs_acl:
#Version 2: (0 calls)
#null        getacl      setacl      getattr     access      getxattrdir 
#0 0%        0 0%        0 0%        0 0%        0 0%        0 0%        
#Version 3: (75540 calls)
#null        getacl      setacl      getxattrdir 
#26342 34%   49196 65%   2 0%        0 0%        


default_values = (1, 3)

def inventory_nfsstat_full(info):

   yield "nfs_rpc", "default_values"
   yield "nfs3stat", "default_values"
   yield "nfs4stat", "default_values"

def check_nfsstat_full(item, params, info):

data = []
    perfdata = []
    message = []
    xmessage= ""
    line_names = []
    line_data = []


    line_number = 0 
    if item=="nfs_rpc":
        for line in info:
    	    if 2 <= line_number <= 5:
		if line_number % 2 ==0 :
		    line_names = line
#		    print str(line)
		else:
		    line_data = line
#		    print str(line)

		if line_number % 2 <>0:
	            tcount=0
	            for tdata in line_names:
	        	    xmessage += str(line_names[tcount])+"="+str(line_data[tcount]) +" "
	        	    perfdata += [ (str(line_names[tcount]) ,  int(line_data[tcount]))  ]
    			    tcount += 1
	    line_number=line_number+1
    		
        return 0,"RPC |"+xmessage, perfdata 


    if item=="nfs3stat":
	line_number = 0 
	perfdata = []
        xmessage = ""
        for line in info:
    	    if 15 <= line_number <= 16:
		if line_number % 2 <>0 :
		    line_names = line
#		    print str(line_names)
		else:
		    line_data = line
#		    print str(line_data)
#		if line_number % 2 <>0:
	            tcount=0
	            for tdata in line_names:
	        	    xmessage += str(line_names[tcount])+"="+str(line_data[tcount]) +" "
	        	    perfdata += [ (str(line_names[tcount]) ,  int(line_data[tcount]))  ]
    			    tcount += 1
	    line_number=line_number+1

###second part
	line_number = 0 
	line_above = []
        for line in info:
    	    if 28 <= line_number <= 39:
		if line_number % 2 ==0 :
		    line_names = line
#		    print str(line_names)
		else:
		    line_data = line
#		    print str(line_data)

#		if line_number % 2==0:
	            tcount=0
	            for tdata in line_names:
	        		xmessage += str(line_names[tcount])+"="+str(line_data[tcount*2]) +" " 
	        		xmessage += str(line_names[tcount])+"_p="+str(line_data[tcount*2+1]) +" " 
	        		perfdata += [ (str(line_names[tcount]) ,  int(line_data[tcount*2]))  ]
				perfdata += [ (str(line_names[tcount])+"_p" ,  str(line_data[tcount*2+1]).replace("%", "") ,"" ,"",0 ,100 ) ]
        			tcount += 1

	    line_number=line_number+1
	return 0,"NFSv3 |"+xmessage, perfdata 

    if item=="nfs4stat":
	line_number = 0 
	perfdata = []
        xmessage = ""
        for line in info:
    	    if 18 <= line_number <= 19:
		if line_number % 2 ==0 :
		    line_names = line
#		    print str(line_names)
		else:
		    line_data = line
#		    print str(line_data)
#		if line_number % 2 <>0:
	            tcount=0
	            for tdata in line_names:
	        	    xmessage += str(line_names[tcount])+"="+str(line_data[tcount]) +" "
	        	    perfdata += [ (str(line_names[tcount]) ,  int(line_data[tcount]))  ]
    			    tcount += 1
	    line_number=line_number+1
#	return 0,"NFSv4 |"+xmessage, perfdata 

###second part
	line_number = 0 
	line_above = []
        for line in info:
    	    if 44 <= line_number <= 63:
		if line_number % 2 ==0 :
		    line_names = line
#		    print str(line_names)
		else:
		    line_data = line
#		    print str(line_data)

#		if line_number % 2==0:
	            tcount=0
	            for tdata in line_names:
	        		xmessage += str(line_names[tcount])+"="+str(line_data[tcount*2]) +" " 
	        		xmessage += str(line_names[tcount])+"_p="+str(line_data[tcount*2+1]) +" " 
	        		perfdata += [ (str(line_names[tcount]) ,  int(line_data[tcount*2]))  ]
				perfdata += [ (str(line_names[tcount])+"_p" ,  str(line_data[tcount*2+1]).replace("%", "") ,"" ,"",0 ,100 ) ]
        			tcount += 1

	    line_number=line_number+1
	return 0,"NFSv4 |"+xmessage, perfdata 





#    for line in info:
#	print str(line_number)+"    "+str(line)
#	line_number=line_number+1






    return 0,"xxaaxx",perfdata 

#  return 3, "Sorry - not implemented"
         
# declare the check to Check_MK
check_info["nfsstat_full"] = {
 'check_function':            check_nfsstat_full,
 'inventory_function':        inventory_nfsstat_full,
 'service_description':       'Solaris nfsstat full %s',
 'has_perfdata':              True,
}
